config/routes.rb
LinkBlog::Application.routes.draw do
  resources :linkages

end

app/models/linkage.rb
class Linkage < ActiveRecord::Base
  attr_accessible :description, :link
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/linkages_controller.rb
class LinkagesController < ApplicationController
  # GET /linkages
  # GET /linkages.json
  def index
    @linkages = Linkage.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @linkages }
    end
  end

  # GET /linkages/1
  # GET /linkages/1.json
  def show
    @linkage = Linkage.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @linkage }
    end
  end

  # GET /linkages/new
  # GET /linkages/new.json
  def new
    @linkage = Linkage.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @linkage }
    end
  end

  # GET /linkages/1/edit
  def edit
    @linkage = Linkage.find(params[:id])
  end

  # POST /linkages
  # POST /linkages.json
  def create
    @linkage = Linkage.new(params[:linkage])

    respond_to do |format|
      if @linkage.save
        format.html { redirect_to @linkage, notice: 'Linkage was successfully created.' }
        format.json { render json: @linkage, status: :created, location: @linkage }
      else
        format.html { render action: "new" }
        format.json { render json: @linkage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /linkages/1
  # PUT /linkages/1.json
  def update
    @linkage = Linkage.find(params[:id])

    respond_to do |format|
      if @linkage.update_attributes(params[:linkage])
        format.html { redirect_to @linkage, notice: 'Linkage was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @linkage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /linkages/1
  # DELETE /linkages/1.json
  def destroy
    @linkage = Linkage.find(params[:id])
    @linkage.destroy

    respond_to do |format|
      format.html { redirect_to linkages_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/linkages_helper.rb
module LinkagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LinkBlog</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/linkages/_form.html.erb
<%= form_for(@linkage) do |f| %>
  <% if @linkage.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@linkage.errors.count, "error") %> prohibited this linkage from being saved:</h2>

      <ul>
      <% @linkage.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :link %><br />
    <%= f.text_field :link %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/linkages/edit.html.erb
<h1>Editing linkage</h1>

<%= render 'form' %>

<%= link_to 'Show', @linkage %> |
<%= link_to 'Back', linkages_path %>

app/views/linkages/index.html.erb
<h1>Listing of Wonderful Links to the World</h1>

<table>
  <tr>
    <th>Tell me a story by sending me to a new place!</h3>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @linkages.each do |linkage| %>
  <tr>
    <td><%= linkage.link %></td>
    <td><%= linkage.description %></td>
    <td><%= link_to 'Show', linkage %></td>
    <td><%= link_to 'Edit', edit_linkage_path(linkage) %></td>
    <td><%= link_to 'Destroy', linkage, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Linkage', new_linkage_path %>

app/views/linkages/new.html.erb
<h1>New linkage</h1>

<%= render 'form' %>

<%= link_to 'Back', linkages_path %>

app/views/linkages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Link:</b>
  <%= @linkage.link %>
</p>

<p>
  <b>Description:</b>
  <%= @linkage.description %>
</p>


<%= link_to 'Edit', edit_linkage_path(@linkage) %> |
<%= link_to 'Back', linkages_path %>
<%= link_to 'New Linkage', new_linkage_path %>